steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/dockerfiles/fomcv2/e2e/Dockerfile:latest', '.']
images: ['gcr.io/${PROJECT_ID}/dockerfiles/fomcv2/e2e/Dockerfile:latest']
