steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'docker.pkg.dev/IOF-B2B-POC-FOMCV2/dockerfiles/fomcv2/e2e/Dockerfile:latest', '.' ]
images:
- 'docker.pkg.dev/IOF-B2B-POC-FOMCV2/dockerfiles/fomcv2/e2e/Dockerfile:latest'