name: Build Docker for TA BIRDS
on:
  push:
    tags:
      - 'birds-ta-v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout # This action checkout your repo under $GITHUB_WORKSPACE, so your workflow can access it.
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x  #input for the action
      - name: package docker
        run: |
          VERSION=$(date +%s)
          docker login docker.pkg.github.com --username smhernandezl --password ${{ secrets.GITHUB_TOKEN}}
          docker build . --file ./dockerfiles/birds/e2e/Dockerfile --tag docker.pkg.github.com/smhernandezl/iof-b2b-ta/e2e-birds-ta:${VERSION} --build-arg username=smhernandezl --build-arg password=${{ secrets.GITHUB_TOKEN}}
          docker push docker.pkg.github.com/smhernandezl/iof-b2b-ta/e2e-birds-ta:${VERSION}
          docker build . --file ./dockerfiles/birds/api/Dockerfile --tag docker.pkg.github.com/smhernandezl/iof-b2b-ta/api-birds-ta:${VERSION} --build-arg username=smhernandezl --build-arg password=${{ secrets.GITHUB_TOKEN}}
          docker push docker.pkg.github.com/smhernandezl/iof-b2b-ta/api-birds-ta:${VERSION}
        env:
          CI: true



